spring.application.name=banhmyking

# Datasource (url/username/password) + server.port nằm ở application-dev.properties
spring.datasource.password=${DB_PASSWORD}
spring.profiles.active=dev

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true